service: snype
app: snype
org: justinyu9

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
  hi:
    handler: src/handler.hi
    events:
      - http:
          method: get
          path: hi
